repos:
    - repo: local
      hooks:
        - id: no_debug
          name: No debug on prod
          types: [python]
          args: [--multiline]
          entry: 'breakpoint\(\)|set_trace'
          language: pygrep

    -   repo: https://github.com/adamchainz/django-upgrade
        rev: "1.20.0"
        hooks:
        -   id: django-upgrade
            args: [--target-version, "4.2"]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v4.6.0'
      hooks:
        -   id: check-yaml
        -   id: check-toml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: mixed-line-ending

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.5.5
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
